export enum StageMutationTypes {
  SET_LIST = 'SET_LIST',
  SET_DETAILS = 'SET_DETAILS',
  START_DRAG = 'START_DRAG',
  MOVE_DRAG = 'MOVE_DRAG',
  END_DRAG = 'END_DRAG',
  SET_SCALE = 'SET_SCALE',
  ADD_STAGE = 'ADD_STAGE',
}

export enum StageActionTypes {
  FETCH_LIST = 'FETCH_LIST',
  FETCH_ONE = 'FETCH_ONE',
  CREATE = 'CREATE',
  SAVE_POSITION = 'SAVE_POSITION',
  CREATE_CONTEXT = 'CREATE_CONTEXT',
}