export enum NodeMutationTypes {
  SET_NODES_LIST = 'SET_NODES_LIST',
  START_DRAG = 'START_DRAG',
  MOVE_DRAG = 'MOVE_DRAG',
  END_DRAG = 'END_DRAG',
  ADD_NODE = 'ADD_NODE',
  REMOVE_NODE = 'REMOVE_NODE',
};


export enum NodeActionTypes {
  FETCH_LIST = 'FETCH_LIST',
  CREATE = 'CREATE',
  SAVE_POSITION = 'SAVE_POSITION',
  DELETE = 'DELETE',
  FETCH_LINKS = 'FETCH_LINKS',
}