export enum LinkActionTypes {
  FETCH_LIST = 'FETCH_LIST',
  DELETE_LINK = 'DELETE_LINK',
  DELETE_PARAM_LINK = 'DELETE_PARAM_LINK',
  DELETE_PARAM_LINKS = 'DELETE_PARAM_LINKS',
}

export enum LinkMutationTypes {
  ADD_LINK = 'ADD_LINK',
  ADD_PARAM_LINK = 'ADD_PARAM_LINK',
  REMOVE_LINK = 'REMOVE_LINK',
  REMOVE_PARAM_LINK = 'REMOVE_PARAM_LINK',
}